### ISSUE TITLE
falling back to next best quality

### ISSUE THREAD

**Issue by Kaiay** [hizkifw/fc2-live-dl#16]
> Requested quality ('3Mbps", 'mid') is not available
> falling back to next best quality ('1.2Mbps', 'mid')

I found that 2Mbps is available in apps (trying though cellular data)
how can I make it falling back to 2Mbps but not 1.2Mbps?
Is it affected by the latency setting?

**Comment by hizkifw** [comment]
Which version of fc2-live-dl are you running? Falling back to 2Mbps is supported regardless of the latency. Can you link me the stream where it doesn't work?

**Comment by Kaiay** [comment]
40740626 stream on 4-3-2022
version v2.0.1
using autofc2.json to start
Checked some of the recorded streams from other members of the same group, seems no one of them have over 1.2Mbps bit rate in videos.
![image](https://user-images.githubusercontent.com/43386053/156899413-b6ae13f8-ce67-4694-aa4e-e0b0e25fe7c8.png)

just afraid setting something wrong...
I will try checking again on tonight けもりふ's member stream.

**Comment by Kaiay** [comment]
72364867 which streaming now
![image](https://user-images.githubusercontent.com/43386053/157876743-7bfb5ed3-0579-400f-abb1-6044fc993972.png)
![IMG_4674](https://user-images.githubusercontent.com/43386053/157877274-5df344a0-0620-42dc-abdf-ae7f73340930.PNG)

**Comment by hizkifw** [comment]
I'm not sure what happened, I'm getting 3Mbps on the web player and also getting 3Mbps using my instance of fc2-live-dl v2.0.1.

```
fc2-live-dl --latency high --quality 3Mbps https://live.fc2.com/72364867
[main] fc2-live-dl v2.0.1 
[fc2 72364867] Fetching stream info 
[fc2 72364867] Found websocket url 
[fc2 72364867] Received HLS info 
[fc2 72364867] Writing stream to 2022-03-11 オナニー実演 (兎野さくら).ts 
^C[fc2 72364867] Interrupted by user 
[fc2 72364867] Remuxing stream to 2022-03-11 オナニー実演 (兎野さくら).1.mp4 
[fc2 72364867] Removing intermediate files 
[fc2 72364867] Done
```

Can you tell me what version of Python you have (`python --version`)? Also, can you try running it [using WSL](https://docs.microsoft.com/en-us/windows/wsl/install)?

**Comment by Kaiay** [comment]
Python 3.10.2
I try terminate it and restart it, then it works on 3Mbps lol don't know what's happening. Closing and thank you.
