### ISSUE TITLE
403 Error every 2 and half minutes 

### ISSUE THREAD

**Issue by CarterJimmy** [hizkifw/fc2-live-dl#4]
Hello.
I've been trying to use this script to download some fc2-live contents.

However, after running the script for about few minutes(specifically, every 2 minutes and 31 seconds), error messages such like `Failed to reload playlist: Unable to open URL` and `Forbidden for url`  (the url followed was the HLS address). And eventually the script was terminated because of the `Read time out` error.

I assume that the reason for this timeout problem is because FC2's HLS address is dynamic and changes every 2 and half minutes. I guessed it this way because if I use the autofc2 script, it will download many separate files and every files has the same length which is 2:31 minutes.

I was wondering if I was the only person facing this problem. If someone can give me a solution to this problem, I would really appreciate it.

FYI, here's some error messages.
![Snipaste_2021-11-08_00-38-31](https://user-images.githubusercontent.com/7923743/140651911-34881f6a-78c6-4cc4-adbf-d076cc321d1a.png)

**Comment by hizkifw** [comment]
I've fixed this issue in the latest version (v1.2.0). Please grab the latest version and open a new issue if you encounter any problems. Thanks.
